# Generated by Django 5.2.6 on 2025-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='username',
            field=models.CharField(default='out', max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
