# Generated by Django 5.2.6 on 2025-09-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
