# Generated by Django 5.2.6 on 2025-09-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userloginlog_email_userloginlog_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='timestamp',
        ),
    ]
